### ISSUE TITLE
Add indication of ES server and index for dev

### ISSUE THREAD

**Issue by kauberry** [pacifica/pacifica-search#17]
Let's put some indication of which Git hash and last commit log entry on the page (under a clickable element on the page or something)

**Comment by BenjaminStuermer** [comment]
This is done - the git hash and commit date are logged to the console when the page loads. I didn't include the commit message because the text is publicly visible and the commit message might not be something we want shared. It's easy enough to find the commit message from the hash if we need it, in any case.

**Comment by BenjaminStuermer** [comment]
@kauberry Can you close this issue?
